# Generated by Django 5.1 on 2024-08-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_cruise_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruise',
            name='image',
            field=models.ImageField(default='', upload_to='cruise/images'),
        ),
    ]
