# Generated by Django 5.1 on 2024-08-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api','0004_alter_cruise_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CruiseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('departure', models.CharField(max_length=100)),
                ('visiting', models.CharField(max_length=1000)),
                ('nights', models.IntegerField(default=0)),
                ('decks', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('seats', models.IntegerField(default=0)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('continent', models.CharField(max_length=100)),
                ('image', models.ImageField(default='', upload_to='cruise/images')),
                ('cruiseName', models.CharField(default='Unnamed Cruise', max_length=100)),
            ],
        ),
    ]
