# Generated by Django 5.1 on 2024-08-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_cruisedetailfinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruise',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='decks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='nights',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='seats',
            field=models.IntegerField(default=0),
        ),
    ]
