# Generated by Django 5.1 on 2024-09-07 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_booking_delete_cruisedetailsdone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date_booked',
        ),
    ]
