# Generated by Django 5.1 on 2024-09-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room_number',
            field=models.CharField(max_length=10),
        ),
    ]
